version: '2'

services:
  app:
     image: 'mail-api-springboot-app:latest'
     build:
       context: .
       dockerfile: Dockerfile
     container_name: app
     depends_on:
       - db
     ports:
       - 8080:8080
     expose:
       - 8080
     environment:
       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/messages_gradle
       - SPRING_DATASOURCE_USERNAME=postgres
       - SPRING_DATASOURCE_PASSWORD=postgres
       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:latest'
    volumes:
      - ./schema/:/docker-entrypoint-initdb.d/
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messages_gradle
