-- public.countries definition

-- Drop table

-- DROP TABLE countries;

CREATE TABLE countries (
	id_country int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	CONSTRAINT countries_pkey PRIMARY KEY (id_country)
);


-- public.recipient_types definition

-- Drop table

-- DROP TABLE recipient_types;

CREATE TABLE recipient_types (
	id_recipient_type int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	acronym varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT recipient_types_pkey PRIMARY KEY (id_recipient_type)
);


-- public.states definition

-- Drop table

-- DROP TABLE states;

CREATE TABLE states (
	id_state int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	id_country int8 NULL,
	CONSTRAINT states_pkey PRIMARY KEY (id_state),
	CONSTRAINT fk_country_state FOREIGN KEY (id_country) REFERENCES countries(id_country)
);


-- public.cities definition

-- Drop table

-- DROP TABLE cities;

CREATE TABLE cities (
	zip_code int8 NOT NULL,
	"name" varchar(255) NULL,
	id_state int8 NULL,
	CONSTRAINT cities_pkey PRIMARY KEY (zip_code),
	CONSTRAINT fk_state_city FOREIGN KEY (id_state) REFERENCES states(id_state)
);


-- public.employees definition

-- Drop table

-- DROP TABLE employees;

CREATE TABLE employees (
	id_employee int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_number varchar(255) NULL,
	last_name varchar(255) NULL,
	mail_username varchar(255) NULL,
	"name" varchar(255) NULL,
	id_city int8 NULL,
	CONSTRAINT employees_pkey PRIMARY KEY (id_employee),
	CONSTRAINT fk_city_employee FOREIGN KEY (id_city) REFERENCES cities(zip_code)
);


-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	id_user int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_admin bool NULL,
	is_enabled bool NULL DEFAULT true,
	"password" varchar(255) NULL,
	username varchar(255) NULL,
	id_employee int8 NULL,
	CONSTRAINT uk_itpfu3avhbnq43s58xiyhvibn UNIQUE (id_employee),
	CONSTRAINT users_pkey PRIMARY KEY (id_user),
	CONSTRAINT fk_employee_user FOREIGN KEY (id_employee) REFERENCES employees(id_employee)
);


-- public.labels definition

-- Drop table

-- DROP TABLE labels;

CREATE TABLE labels (
	id_label int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	enabled bool NULL DEFAULT true,
	"name" varchar(255) NULL,
	id_user int4 NULL,
	CONSTRAINT labels_pkey PRIMARY KEY (id_label),
	CONSTRAINT fk_user_label FOREIGN KEY (id_user) REFERENCES users(id_user)
);


-- public.messages definition

-- Drop table

-- DROP TABLE messages;

CREATE TABLE messages (
	id_message int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	body varchar(255) NULL,
	datee timestamp NULL,
	is_deleted_by_user_from bool NULL DEFAULT false,
	subject varchar(255) NULL,
	id_user_from int4 NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id_message),
	CONSTRAINT fk_user_from FOREIGN KEY (id_user_from) REFERENCES users(id_user)
);


-- public.recipients definition

-- Drop table

-- DROP TABLE recipients;

CREATE TABLE recipients (
	id_recipient int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_deleted_by_recipient bool NULL DEFAULT false,
	id_message int4 NULL,
	id_recipient_type int4 NULL,
	id_user int4 NULL,
	CONSTRAINT recipients_pkey PRIMARY KEY (id_recipient),
	CONSTRAINT fk_message_recipient FOREIGN KEY (id_message) REFERENCES messages(id_message),
	CONSTRAINT fk_type_recipient FOREIGN KEY (id_recipient_type) REFERENCES recipient_types(id_recipient_type),
	CONSTRAINT fk_user_recipient FOREIGN KEY (id_user) REFERENCES users(id_user)
);


-- public.attatchments definition

-- Drop table

-- DROP TABLE attatchments;

CREATE TABLE attatchments (
	id_attachment int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	attachment varchar(255) NULL,
	id_message int4 NULL,
	CONSTRAINT attatchments_pkey PRIMARY KEY (id_attachment),
	CONSTRAINT fk_message_attachment FOREIGN KEY (id_message) REFERENCES messages(id_message)
);


-- public.labels_x_messages definition

-- Drop table

-- DROP TABLE labels_x_messages;

CREATE TABLE labels_x_messages (
	id_label_x_message int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_label int4 NULL,
	id_message int4 NULL,
	id_user int4 NULL,
	CONSTRAINT labels_x_messages_pkey PRIMARY KEY (id_label_x_message),
	CONSTRAINT fk_label_message FOREIGN KEY (id_label) REFERENCES labels(id_label),
	CONSTRAINT fk_message_label FOREIGN KEY (id_message) REFERENCES messages(id_message),
	CONSTRAINT fk_user_label_message FOREIGN KEY (id_user) REFERENCES users(id_user)
);


insert into countries(name) values ('Argentina');

insert into states(name, id_country) values ('Buenos Aires', 1);

insert into cities(zip_code, name, id_state) values (7600, 'Mar del Plata', 1);

insert into employees(id_number,name, last_name, mail_username, id_city) values ('1234567', 'Pedro', 'Rodriguez', 'pepe', 7600);
insert into employees(id_number,name, last_name, mail_username, id_city) values ('1234568', 'Jorge', 'Perez', 'jorge-perez', 7600);
insert into employees(id_number,name, last_name, mail_username, id_city) values ('1234568', 'Ana', 'Perez', 'ana-perez', 7600);

/*password 1234*/
insert into users(username, password, is_admin, id_employee) values ('Pepe Rodriguez','81dc9bdb52d04dc20036dbd8313ed055', true, 1);
insert into users(username, password, is_admin, id_employee) values ('Jorge Perez','81dc9bdb52d04dc20036dbd8313ed055', false, 2);


insert into recipient_types (name, acronym) values ('Primary Receptor', 'To'), ('Carbon Copy', 'CC'),('Blind Carbon Copy', 'BCC');

/*Default*/
insert into labels(name, id_user) values ('Important',null), ('Spam',null);

/*UserLabels*/
insert into labels(name, id_user) values ('Family',1), ('Bank',1), ('Work',2);
insert into labels(name,id_user) values ('Label',2);

insert into messages(subject, body, datee, id_user_from) values ('First Message', 'Hi! How are you?','2021-04-23 11:05:07', 1);
insert into messages(subject, body, datee, id_user_from) values ('Second Message', 'Bye!', '2021-04-23 11:05:07', 1);

insert into recipients (id_message, id_recipient_type, id_user) values (1,1,2);
insert into recipients (id_message, id_recipient_type, id_user) values (1,3,2);


insert into labels_x_messages (id_label, id_message,id_user) values (1,1,1);
insert into labels_x_messages (id_label, id_message,id_user) values (3,1,1);
insert into labels_x_messages (id_label, id_message,id_user) values (5,1,2);
insert into labels_x_messages (id_label, id_message,id_user) values (1,1,2);